project:
  type: website

website:
  title: "Visual Analytics and Applications - Group 4"
  navbar:
    left:
      - href: challenge.qmd
        text: The Challenge
      - href: proposal.qmd
        text: Proposal
      - text: "The Goods"
        menu:
          - text: "R Shiny App"
            href: ""
          - text: "Poster"
            href: ""
    right: 
      - href: index.qmd
        text: Home
      - href: team.qmd
        text: The Team
format:
  html: 
    theme: lux
    css: styles.css
    toc: true
    
editor: visual
